In [1]:
import torch
import numpy as np

还有很多函数可以创建Tensor，去翻翻官方API就知道了，下表给了一些常用的作参考。

函数	功能
Tensor(*sizes)	基础构造函数
tensor(data,)	类似np.array的构造函数
ones(*sizes)	全1Tensor
zeros(*sizes)	全0Tensor
eye(*sizes)	对角线为1，其他为0
arange(s,e,step)	从s到e，步长为step
linspace(s,e,steps)	从s到e，均匀切分成steps份
rand/randn(*sizes)	均匀/标准分布
normal(mean,std)/uniform(from,to)	正态分布/均匀分布
randperm(m)	随机排列
这些创建方法都可以在创建的时候指定数据类型dtype和存放device(cpu/gpu)。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
X.numel()

In [14]:
data_zeros = torch.zeros((2, 3, 4))
data_zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
data_zeros = torch.zeros((3, 4))
data_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
data_randn = torch.randn(3, 4)
data_randn

tensor([[-1.6297, -0.2464,  0.8536,  0.5848],
        [ 0.7358, -1.7256,  0.3954, -0.5017],
        [-0.0809, -0.2169,  1.5887,  0.3184]])

In [19]:
torch.tensor([[1, 2]
                 , [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [25]:
data = torch.tensor([[[1, 2, 3]
                         , [4, 5, 6]
                         , [7, 8, 9]]])
data.shape

torch.Size([1, 3, 3])

In [26]:
np_array = torch.tensor(np.arange(10))
np_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6536, 0.8978, 0.7627],
        [0.8673, 0.2693, 0.7565]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
tensor = torch.rand(3, 4)
print(f"{tensor.shape}")
print(f"{tensor.dtype}")
print(f"{tensor.device}")

torch.Size([3, 4])
torch.float32
cpu


## 张量运算


1. 张量的索引和切片

In [34]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

2. 张量的拼接


In [37]:
torch_cat = torch.cat([tensor, tensor, tensor], dim = 0)
torch_cat.shape

torch.Size([12, 4])

3. 张量的乘积和矩阵乘法

In [38]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [39]:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [40]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [41]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

4. 自动赋值运算

In [42]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


5. Tensor与Numpy的转换

In [47]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


转换得来的numpy与torch共享同一块内存

In [49]:
t.add_(1)
print(t)
print(n)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


numpy转换为张量

In [52]:
n = np.ones(5)
t = torch.tensor(n)
t1 = torch.from_numpy(n)
print(t)
print(t1)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
